"""
Two-orbit ansatz at LARGER m values for Erdős Problem #97.

Extends prior tests at m in {6,7,8,9,10,12} (perturbation_analysis.py /
symmetric_search.py) to m in {14, 15, 16, 18, 20, 25, 30}, i.e.
n in {28, 30, 32, 36, 40, 50, 60}.

Setup
-----
A_i = (cos(2 pi i/m), sin(2 pi i/m))                  outer (R = 1)
B_i = r_b (cos(2 pi i/m + pi/m + phi), sin(...))      inner (offset pi/m + phi)

Total n = 2m vertices. We want every vertex to have a 4-witness equal-distance
multiset within the strict-convex window for r_b in (cos(pi/m), 1/cos(pi/m)),
phi in approximately (-pi/m, pi/m).

By dihedral symmetry C_m generated by simultaneous rotation of both orbits, it
suffices to enforce 4-equality at ONE outer (A_0) and ONE inner (B_0)
representative; all others follow by C_m rotation. The remaining freedom is
two parameters (r_b, phi); we therefore impose two equality conditions:
choose two pairs of witnesses (one at each representative vertex) and require
equal selected distances.

Distance formulas
-----------------
At outer A_0:
    D_AA(a)        = 2 - 2 cos(2 pi a/m)
    D_AB(b; r,phi) = 1 + r^2 - 2 r cos(2 pi b/m + pi/m + phi)
At inner B_0:
    D_BB(a; r)     = 2 r^2 (1 - cos(2 pi a/m))
    D_BA(b; r,phi) = 1 + r^2 - 2 r cos(2 pi b/m - pi/m - phi)

Witness-pattern equations (single equation per representative vertex)
---------------------------------------------------------------------
Outer A_0 patterns:
   (Oa) 2 outer + 2 inner: pair-class (a, m-a) outer + pair-class (b1, -1-b1) inner
        Equation: D_AA(a) = D_AB(b1)
   (Ob) 0 outer + 4 inner: two distinct pair-classes (b1, -1-b1), (b2, -1-b2)
        Equation: D_AB(b1) = D_AB(b2)   (depends only on phi)

Inner B_0 patterns:
   (Ia) 2 inner + 2 outer: pair-class (a, m-a) inner + pair-class (b1, 1-b1) outer
        Equation: D_BB(a) = D_BA(b1)
   (Ib) 0 inner + 4 outer: two outer pair-classes (b1, 1-b1), (b2, 1-b2)
        Equation: D_BA(b1) = D_BA(b2)   (depends only on phi)

Note: 4-outer-only at A_0 forces D_AA(a1)=D_AA(a2), no parameter -> only same
pair-class -> degenerate. Same for 4-inner-only at B_0. Skipped.

Equation-level reductions (closed form)
---------------------------------------
- Each (Oa)/(Ia) equation is a quadratic in r for fixed phi:
        Oa:  r^2 - 2 r cos(2 pi b/m + pi/m + phi) + (1 - 2 + 2 cos(2 pi a/m)) = 0
              i.e. r^2 - 2 c_O(b,phi) r + (2 cos(2 pi a/m) - 1) = 0
        Ia:  (4 sin^2(pi a/m)) r^2 - 2 c_I(b,phi) r + ... wait, recompute:
              D_BB - D_BA = 2 r^2 (1 - cos 2 pi a/m) - (1 + r^2 - 2 r c_I)
                          = (1 - 2 cos 2 pi a/m) r^2 + 2 r c_I - 1 = 0
- Each (Ob)/(Ib) equation is purely a phi-equation:
        D_AB(b1) - D_AB(b2)
            = -2 r [cos(2 pi b1/m + pi/m + phi) - cos(2 pi b2/m + pi/m + phi)]
        = 0  iff  cos(2 pi b1/m + pi/m + phi) = cos(2 pi b2/m + pi/m + phi)
        => phi = -pi/m - pi (b1+b2)/m  or  forces b1 == b2 -> degenerate.

Combining (Oa) at outer and (Ia) at inner gives a 2-eq system in (r, phi).
Combining (Ob) at outer and (Ia) at inner: solve (Ob) for phi (closed form),
then (Ia) becomes a single quadratic in r.
Combining (Oa) at outer and (Ib) at inner: solve (Ib) for phi, then (Oa)
becomes a single quadratic in r.
Combining (Ob) at outer and (Ib) at inner: phi over-determined by two
constraints; succeed iff both yield consistent phi.

We use closed-form roots (vectorised via numpy) for tractable speed
even at m = 30.

Convex window
-------------
r in (cos(pi/m), sec(pi/m)),  abs(phi) < pi/m.

Strict convexity in alternating cyclic order A_0, B_0, A_1, B_1, ...
checked numerically.

All-vertex 4-bad checked at the end.

Output
------
/home/user/erdos97/data/certificates/2026-05-06/two_orbit_large_m.json
"""
from __future__ import annotations

import json
import math
import time
from itertools import combinations

import numpy as np


# ------------------------------------------------------------------
# Geometry helpers
# ------------------------------------------------------------------

def build_two_orbit(m, r_b, phi):
    """2m points: alternating outer (R=1) and inner (r_b) at offset pi/m + phi.
    Indices: outer i -> 2i, inner i -> 2i+1, so the natural cyclic order is
    A_0, B_0, A_1, B_1, ..."""
    pts = np.zeros((2 * m, 2))
    h = math.pi / m
    for i in range(m):
        ang_o = 2 * math.pi * i / m
        pts[2 * i] = (math.cos(ang_o), math.sin(ang_o))
        ang_i = ang_o + h + phi
        pts[2 * i + 1] = (r_b * math.cos(ang_i), r_b * math.sin(ang_i))
    return pts


def cyclic_strictly_convex(P, eps=1e-10):
    n = len(P)
    sgn = None
    for i in range(n):
        a = P[i]
        b = P[(i + 1) % n]
        c = P[(i + 2) % n]
        cross = (b[0] - a[0]) * (c[1] - b[1]) - (b[1] - a[1]) * (c[0] - b[0])
        if abs(cross) < eps:
            return False
        s = 1 if cross > 0 else -1
        if sgn is None:
            sgn = s
        elif s != sgn:
            return False
    return True


def all_vertex_4bad(P, tol=1e-6):
    n = len(P)
    # Pairwise distance matrix
    D = np.linalg.norm(P[:, None, :] - P[None, :, :], axis=2)
    for i in range(n):
        ds = np.sort(np.delete(D[i], i))
        # check largest cluster
        clusters = [[ds[0]]]
        for d in ds[1:]:
            if d - clusters[-1][-1] < tol:
                clusters[-1].append(d)
            else:
                clusters.append([d])
        if max(len(c) for c in clusters) < 4:
            return False
    return True


# ------------------------------------------------------------------
# Closed-form quadratic helpers
# ------------------------------------------------------------------

def quad_roots(a, b, c):
    """Real roots of a x^2 + b x + c, returned sorted ascending. NaN if none."""
    if abs(a) < 1e-15:
        if abs(b) < 1e-15:
            return []
        return [-c / b]
    disc = b * b - 4 * a * c
    if disc < -1e-14:
        return []
    if disc < 0:
        disc = 0.0
    sd = math.sqrt(disc)
    return sorted([(-b - sd) / (2 * a), (-b + sd) / (2 * a)])


def solve_Oa_for_r(a, b1, m, phi):
    """Outer 'Oa' equation D_AA(a) = D_AB(b1) =>
       r^2 - 2 cos(2 pi b1/m + pi/m + phi) r + (1 - D_AA(a)) = 0
       i.e. r^2 - 2 c r + (1 - 2 + 2 cos(2 pi a/m)) = 0
            r^2 - 2 c r + (2 cos(2 pi a/m) - 1) = 0
    """
    c_O = math.cos(2 * math.pi * b1 / m + math.pi / m + phi)
    cst = 2 * math.cos(2 * math.pi * a / m) - 1
    return quad_roots(1.0, -2 * c_O, cst)


def solve_Ia_for_r(a, b1, m, phi):
    """Inner 'Ia' equation D_BB(a) = D_BA(b1):
       2 r^2 (1 - cos(2 pi a/m)) - (1 + r^2 - 2 r cos(2 pi b1/m - pi/m - phi)) = 0
       (2 (1 - cos t_a) - 1) r^2 + 2 cos(b1) r - 1 = 0
       (1 - 2 cos t_a) r^2 + 2 c_I r - 1 = 0
    """
    A = 1.0 - 2.0 * math.cos(2 * math.pi * a / m)
    c_I = math.cos(2 * math.pi * b1 / m - math.pi / m - phi)
    return quad_roots(A, 2 * c_I, -1.0)


def solve_Ob_for_phi_candidates(b1, b2, m):
    """Outer 'Ob' equation: cos(2 pi b1/m + pi/m + phi) = cos(2 pi b2/m + pi/m + phi).
    Let u_i = 2 pi b_i/m + pi/m. cos(u1+phi) = cos(u2+phi) ->
       u1+phi = +-(u2+phi) + 2k pi.
    The + branch -> u1=u2 (impossible since b1 != b2).
    The - branch -> phi = -(u1+u2)/2 + k pi  (mod 2 pi).
    Return the unique-modulo-pi value(s) in (-pi/m, pi/m].
    """
    u1 = 2 * math.pi * b1 / m + math.pi / m
    u2 = 2 * math.pi * b2 / m + math.pi / m
    base = -(u1 + u2) / 2.0
    cands = []
    for k in range(-3, 4):
        phi = base + k * math.pi
        # reduce into (-pi/m, pi/m]
        # We want abs(phi) <= pi/m * 0.9999 typically
        cands.append(phi)
    return cands


def solve_Ib_for_phi_candidates(b1, b2, m):
    """Inner 'Ib' equation: cos(2 pi b1/m - pi/m - phi) = cos(2 pi b2/m - pi/m - phi).
    Let u_i = 2 pi b_i/m - pi/m. cos(u1-phi)=cos(u2-phi) ->
       u1-phi = +-(u2-phi) + 2k pi.
    + branch: u1=u2 (impossible).
    - branch: u1 - phi = -(u2-phi) + 2k pi -> 2 phi = u1 + u2 + ... wait
       u1 - phi = -u2 + phi + 2k pi  -> 2 phi = u1 + u2 - 2 k pi
       phi = (u1+u2)/2 - k pi
    """
    u1 = 2 * math.pi * b1 / m - math.pi / m
    u2 = 2 * math.pi * b2 / m - math.pi / m
    base = (u1 + u2) / 2.0
    cands = []
    for k in range(-3, 4):
        phi = base + k * math.pi
        cands.append(phi)
    return cands


# ------------------------------------------------------------------
# Distance functions for residual / verification
# ------------------------------------------------------------------

def D_AA(a, m):
    return 2.0 - 2.0 * math.cos(2 * math.pi * a / m)


def D_AB(b, m, r, phi):
    return 1.0 + r * r - 2.0 * r * math.cos(2 * math.pi * b / m + math.pi / m + phi)


def D_BB(a, m, r):
    return 2.0 * r * r * (1.0 - math.cos(2 * math.pi * a / m))


def D_BA(b, m, r, phi):
    return 1.0 + r * r - 2.0 * r * math.cos(2 * math.pi * b / m - math.pi / m - phi)


# ------------------------------------------------------------------
# Pattern enumeration
# ------------------------------------------------------------------

def outer_Oa_patterns(m):
    """List of (a, b1, b2). a in [1, m//2], 2a != m. b1 < b2, b1+b2 == -1 mod m."""
    out = []
    half = m // 2
    for a in range(1, half + 1):
        if 2 * a == m:
            continue
        for b1 in range(m):
            b2 = (-1 - b1) % m
            if b1 < b2:
                out.append((a, b1, b2))
    return out


def outer_Ob_patterns(m):
    """List of ((b1a, b1b), (b2a, b2b)) for distinct outer-block pair-classes."""
    pcs = []
    for b1 in range(m):
        b2 = (-1 - b1) % m
        if b1 < b2:
            pcs.append((b1, b2))
    return list(combinations(pcs, 2))


def inner_Ia_patterns(m):
    out = []
    half = m // 2
    for a in range(1, half + 1):
        if 2 * a == m:
            continue
        for b1 in range(m):
            b2 = (1 - b1) % m
            if b1 < b2:
                out.append((a, b1, b2))
    return out


def inner_Ib_patterns(m):
    pcs = []
    for b1 in range(m):
        b2 = (1 - b1) % m
        if b1 < b2:
            pcs.append((b1, b2))
    return list(combinations(pcs, 2))


# ------------------------------------------------------------------
# Solver: each combination
# ------------------------------------------------------------------

def all_outer_a_for_phi_r(m, phi, r):
    """For diagnostic: which outer pair-classes equal D_AB(b1) for this (r, phi)?"""
    d_aa = [D_AA(a, m) for a in range(m)]
    return d_aa


def normalize_phi(phi, m):
    """Reduce phi into the interval (-pi/m, pi/m]."""
    P = 2 * math.pi / m
    phi_n = ((phi + math.pi / m) % P) - math.pi / m
    return phi_n


def solve_combinations_Oa_Ia(m, oa_list, ia_list, cm, cM, tol_resid=1e-9, n_seed=11):
    """For each (Oa) outer eq + (Ia) inner eq, the system has 2 unknowns (r, phi)
    and 2 equations. Use polynomial elimination:
      Oa: r^2 - 2 r cos(u_O + phi) + (2 cos t_a - 1) = 0
      Ia: (1 - 2 cos t_{a'}) r^2 + 2 r cos(u_I - phi) - 1 = 0
    where u_O = 2 pi b1_O/m + pi/m, u_I = 2 pi b1_I/m - pi/m.
    Strategy: parametrise phi over a fine 1D grid, solve quadratic for r at each
    phi from the Oa equation, then check Ia residual; collect (r, phi) where Ia
    residual ~= 0 by Newton. With closed-form quadratic + Newton in 1D this is
    fast.
    Returns list of (r, phi, oa, ia, residual) survivors.
    """
    survivors = []
    # phi-grid (we will refine each)
    phi_grid = np.linspace(-math.pi / m * 0.9999, math.pi / m * 0.9999, n_seed * 4)
    for (a_O, bO1, bO2) in oa_list:
        cst_O = 2 * math.cos(2 * math.pi * a_O / m) - 1
        u_O = 2 * math.pi * bO1 / m + math.pi / m
        for (a_I, bI1, bI2) in ia_list:
            A_I = 1.0 - 2.0 * math.cos(2 * math.pi * a_I / m)
            u_I = 2 * math.pi * bI1 / m - math.pi / m
            # Define h(phi) = Ia residual using the r from Oa
            def Hboth(phi):
                # roots of Oa quadratic
                rr = quad_roots(1.0, -2 * math.cos(u_O + phi), cst_O)
                if not rr:
                    return None
                vals = []
                for r in rr:
                    # Ia residual
                    if r <= 0 or r > 100:
                        continue
                    val = A_I * r * r + 2 * r * math.cos(u_I - phi) - 1.0
                    vals.append((r, val))
                return vals

            # Sample on grid: track residual sign
            grid_eval = []
            for phi in phi_grid:
                pairs = Hboth(phi)
                if pairs is None:
                    continue
                grid_eval.append((phi, pairs))
            # Find sign changes per "branch index" 0,1
            for branch in (0, 1):
                seq = []
                for phi, pairs in grid_eval:
                    if branch < len(pairs):
                        seq.append((phi, pairs[branch][0], pairs[branch][1]))
                # bisect on each consecutive sign change
                for k in range(len(seq) - 1):
                    phi_a, _, va = seq[k]
                    phi_b, _, vb = seq[k + 1]
                    if math.isnan(va) or math.isnan(vb):
                        continue
                    if va * vb > 0:
                        continue
                    # bisect in phi
                    lo, hi = phi_a, phi_b
                    flo = va
                    _ = vb
                    for _ in range(80):
                        mid = (lo + hi) / 2
                        pairs = Hboth(mid)
                        if pairs is None or branch >= len(pairs):
                            break
                        rmid, fmid = pairs[branch]
                        if abs(fmid) < tol_resid:
                            break
                        if flo * fmid <= 0:
                            hi = mid
                        else:
                            lo, flo = mid, fmid
                    pairs = Hboth(mid)
                    if pairs is None or branch >= len(pairs):
                        continue
                    rmid, fmid = pairs[branch]
                    if abs(fmid) > tol_resid:
                        continue
                    if rmid <= 0:
                        continue
                    survivors.append({
                        "outer_pattern": ("Oa", a_O, bO1, bO2),
                        "inner_pattern": ("Ia", a_I, bI1, bI2),
                        "r": rmid,
                        "phi": normalize_phi(mid, m),
                        "phi_unnormalized": mid,
                        "Ia_residual": fmid,
                    })
    return survivors


def solve_combinations_Ob_Ia(m, ob_list, ia_list, tol_resid=1e-9):
    """Outer 'Ob' (block of 4 inner) gives a closed-form phi.
    Then Ia gives a quadratic in r: (1-2 cos t_a) r^2 + 2 r cos(u_I - phi) - 1 = 0.
    """
    survivors = []
    for ((bO1a, bO1b), (bO2a, bO2b)) in ob_list:
        phi_cands = solve_Ob_for_phi_candidates(bO1a, bO2a, m)
        for phi_raw in phi_cands:
            phi = normalize_phi(phi_raw, m)
            if abs(phi) > math.pi / m * 0.9999:
                continue
            for (a_I, bI1, bI2) in ia_list:
                A_I = 1.0 - 2.0 * math.cos(2 * math.pi * a_I / m)
                u_I = 2 * math.pi * bI1 / m - math.pi / m
                rs = quad_roots(A_I, 2 * math.cos(u_I - phi), -1.0)
                for r in rs:
                    if r <= 0 or r > 100:
                        continue
                    # verify Ob residual
                    res_Ob = (
                        D_AB(bO1a, m, r, phi) - D_AB(bO2a, m, r, phi)
                    )
                    if abs(res_Ob) > tol_resid:
                        continue
                    survivors.append({
                        "outer_pattern": ("Ob", bO1a, bO1b, bO2a, bO2b),
                        "inner_pattern": ("Ia", a_I, bI1, bI2),
                        "r": r,
                        "phi": phi,
                        "Ob_residual": res_Ob,
                    })
    return survivors


def solve_combinations_Oa_Ib(m, oa_list, ib_list, tol_resid=1e-9):
    """Inner 'Ib' gives closed-form phi. Then Oa gives a quadratic in r."""
    survivors = []
    for ((bI1a, bI1b), (bI2a, bI2b)) in ib_list:
        phi_cands = solve_Ib_for_phi_candidates(bI1a, bI2a, m)
        for phi_raw in phi_cands:
            phi = normalize_phi(phi_raw, m)
            if abs(phi) > math.pi / m * 0.9999:
                continue
            for (a_O, bO1, bO2) in oa_list:
                cst_O = 2 * math.cos(2 * math.pi * a_O / m) - 1
                u_O = 2 * math.pi * bO1 / m + math.pi / m
                rs = quad_roots(1.0, -2 * math.cos(u_O + phi), cst_O)
                for r in rs:
                    if r <= 0 or r > 100:
                        continue
                    res_Ib = (
                        D_BA(bI1a, m, r, phi) - D_BA(bI2a, m, r, phi)
                    )
                    if abs(res_Ib) > tol_resid:
                        continue
                    survivors.append({
                        "outer_pattern": ("Oa", a_O, bO1, bO2),
                        "inner_pattern": ("Ib", bI1a, bI1b, bI2a, bI2b),
                        "r": r,
                        "phi": phi,
                        "Ib_residual": res_Ib,
                    })
    return survivors


def solve_combinations_Ob_Ib(m, ob_list, ib_list, tol_resid=1e-9):
    """Both phi-only equations: succeed only if same phi works for both."""
    survivors = []
    # precompute phi for each Ob, Ib
    ob_phis = {idx: solve_Ob_for_phi_candidates(b[0][0], b[1][0], m)
               for idx, b in enumerate(ob_list)}
    ib_phis = {idx: solve_Ib_for_phi_candidates(b[0][0], b[1][0], m)
               for idx, b in enumerate(ib_list)}
    for io, ob in enumerate(ob_list):
        for ii, ib in enumerate(ib_list):
            for poa in ob_phis[io]:
                for pib in ib_phis[ii]:
                    if abs(normalize_phi(poa - pib, m)) > 1e-6:
                        continue
                    phi = normalize_phi(poa, m)
                    if abs(phi) > math.pi / m * 0.9999:
                        continue
                    # r free: any r in window. Try midpoint and refine? r unconstrained
                    # by these equations alone, so we don't have a unique r.
                    # In practice all-vertex 4-bad will then determine r via additional
                    # forced equalities. We skip this case to avoid spurious survivors;
                    # user can examine grid scan post-hoc.
                    survivors.append({
                        "outer_pattern": ("Ob", ob[0][0], ob[0][1], ob[1][0], ob[1][1]),
                        "inner_pattern": ("Ib", ib[0][0], ib[0][1], ib[1][0], ib[1][1]),
                        "r": None,  # unconstrained
                        "phi": phi,
                        "phi_consistent": True,
                    })
    return survivors


# ------------------------------------------------------------------
# Master search per m
# ------------------------------------------------------------------

def grid_scan_4bad(m, n_r=80, n_phi=41, tol_4bad=1e-6, eps_conv=1e-11):
    """Brute-force 2D grid scan over the convex window: find any (r, phi)
    inside (cos(pi/m), sec(pi/m)) x (-pi/m, pi/m) where the constructed
    polygon is strictly convex AND every vertex has multiplicity >= 4.
    Returns list of all such hits, plus the best near-miss."""
    cm = math.cos(math.pi / m)
    cM = 1.0 / cm
    rs = np.linspace(cm + 1e-3, cM - 1e-3, n_r)
    phis = np.linspace(-math.pi / m * 0.9999, math.pi / m * 0.9999, n_phi)
    hits = []
    best_near = None
    best_score = -1
    for r in rs:
        for phi in phis:
            pts = build_two_orbit(m, r, phi)
            if not cyclic_strictly_convex(pts, eps=eps_conv):
                continue
            # Compute multiplicities at every vertex
            n = len(pts)
            D = np.linalg.norm(pts[:, None, :] - pts[None, :, :], axis=2)
            min_mult = 1e9
            ok = True
            for i in range(n):
                ds = np.sort(np.delete(D[i], i))
                clusters = [[ds[0]]]
                for d in ds[1:]:
                    if d - clusters[-1][-1] < tol_4bad:
                        clusters[-1].append(d)
                    else:
                        clusters.append([d])
                mx = max(len(c) for c in clusters)
                min_mult = min(min_mult, mx)
                if mx < 4:
                    ok = False
            if ok:
                hits.append({"r": float(r), "phi": float(phi),
                             "min_mult": int(min_mult)})
            elif min_mult > best_score:
                best_score = int(min_mult)
                best_near = {"r": float(r), "phi": float(phi),
                             "min_mult": int(min_mult)}
    return hits, best_near


def search_m(m, tol_resid=1e-9, tol_4bad=1e-6, max_record=20):
    cm = math.cos(math.pi / m)
    cM = 1.0 / cm

    oa = outer_Oa_patterns(m)
    ob = outer_Ob_patterns(m)
    ia = inner_Ia_patterns(m)
    ib = inner_Ib_patterns(m)

    print(f"  patterns Oa={len(oa)} Ob={len(ob)} Ia={len(ia)} Ib={len(ib)}",
          flush=True)

    candidates = []

    # 1) Oa + Ia (most common)
    t0 = time.time()
    cands_aa = solve_combinations_Oa_Ia(m, oa, ia, cm, cM, tol_resid=tol_resid)
    print(f"  Oa+Ia: {len(cands_aa)} candidates ({time.time()-t0:.1f}s)", flush=True)
    candidates += cands_aa

    # 2) Ob + Ia
    t0 = time.time()
    cands_ba = solve_combinations_Ob_Ia(m, ob, ia, tol_resid=tol_resid)
    print(f"  Ob+Ia: {len(cands_ba)} candidates ({time.time()-t0:.1f}s)", flush=True)
    candidates += cands_ba

    # 3) Oa + Ib
    t0 = time.time()
    cands_ab = solve_combinations_Oa_Ib(m, oa, ib, tol_resid=tol_resid)
    print(f"  Oa+Ib: {len(cands_ab)} candidates ({time.time()-t0:.1f}s)", flush=True)
    candidates += cands_ab

    # 4) Ob + Ib (phi-only consistency)
    t0 = time.time()
    cands_bb = solve_combinations_Ob_Ib(m, ob, ib, tol_resid=tol_resid)
    print(f"  Ob+Ib: {len(cands_bb)} candidates with phi-consistent ({time.time()-t0:.1f}s)",
          flush=True)
    # for these the r is unconstrained: we will scan r to look for a strict-convex 4-bad sweet spot
    if cands_bb and len(cands_bb) <= 200:
        for c in cands_bb:
            phi = c["phi"]
            best = None
            for r in np.linspace(cm + 1e-3, cM - 1e-3, 31):
                pts = build_two_orbit(m, r, phi)
                if not cyclic_strictly_convex(pts):
                    continue
                # check 4-bad
                bad = all_vertex_4bad(pts, tol=tol_4bad)
                if bad:
                    best = (float(r), True)
                    break
            c["r_strict_convex_4bad"] = best
            if best is not None:
                c["r"] = best[0]
                candidates.append(c)

    # ----- Verify each candidate -----
    survivors = []
    near_misses = []
    n_in_window = 0
    n_strictly_convex = 0
    best_in_window_residual = math.inf
    best_record = None

    for c in candidates:
        r = c.get("r")
        phi = c.get("phi")
        if r is None or phi is None:
            continue
        in_window = (cm < r < cM)
        if in_window:
            n_in_window += 1
        pts = build_two_orbit(m, r, phi)
        conv = cyclic_strictly_convex(pts, eps=1e-11)
        if conv:
            n_strictly_convex += 1
        bad = all_vertex_4bad(pts, tol=tol_4bad)
        rec = {
            **c,
            "m": m,
            "n": 2 * m,
            "in_convex_window": in_window,
            "strictly_convex_alternating": conv,
            "all_vertex_4bad": bad,
            "convexity_window": [cm, cM],
        }
        # quantify residual: distance from chosen 4-equality to actual
        # use simple: take the witness sets and compute the 4 distances and
        # measure max - min spread.
        # (we recover the witness sets from outer_pattern / inner_pattern)
        op = c.get("outer_pattern")
        ip = c.get("inner_pattern")
        residual_spread = compute_witness_residual(op, ip, m, r, phi)
        rec["witness_residual_spread"] = residual_spread

        if in_window:
            if residual_spread < best_in_window_residual:
                best_in_window_residual = residual_spread
                best_record = rec
        if conv and bad and in_window:
            survivors.append(rec)
        elif in_window and (conv or bad):
            near_misses.append(rec)

    # Also do brute-force 2D grid scan in the convex window
    t0 = time.time()
    grid_hits, grid_best_near = grid_scan_4bad(m, n_r=60, n_phi=31, tol_4bad=tol_4bad)
    print(f"  grid scan: {len(grid_hits)} hits, best near-miss min_mult="
          f"{grid_best_near['min_mult'] if grid_best_near else None} "
          f"({time.time()-t0:.1f}s)", flush=True)

    return {
        "m": m,
        "n": 2 * m,
        "convex_window": [cm, cM],
        "n_candidates": len(candidates),
        "n_in_convex_window": n_in_window,
        "n_strictly_convex": n_strictly_convex,
        "survivors": survivors,
        "near_misses_in_window": near_misses[:max_record],
        "best_record_in_window": best_record,
        "best_residual_in_window": (
            None if best_record is None else best_in_window_residual
        ),
        "grid_scan_hits": grid_hits,
        "grid_scan_best_near_miss": grid_best_near,
    }


def compute_witness_residual(outer_pattern, inner_pattern, m, r, phi):
    """Return the worst-case |D - mean| spread over the union witness set,
    a small number = the chosen 4 distances are nearly equal at A_0 / B_0."""
    if outer_pattern is None or inner_pattern is None:
        return None
    out_kind = outer_pattern[0]
    in_kind = inner_pattern[0]
    pts_outer_d2 = []
    pts_inner_d2 = []
    if out_kind == "Oa":
        a_O, bO1, bO2 = outer_pattern[1], outer_pattern[2], outer_pattern[3]
        pts_outer_d2 = [
            D_AA(a_O, m),
            D_AA((m - a_O) % m, m),
            D_AB(bO1, m, r, phi),
            D_AB(bO2, m, r, phi),
        ]
    elif out_kind == "Ob":
        b1a, b1b, b2a, b2b = outer_pattern[1:]
        pts_outer_d2 = [
            D_AB(b1a, m, r, phi),
            D_AB(b1b, m, r, phi),
            D_AB(b2a, m, r, phi),
            D_AB(b2b, m, r, phi),
        ]
    if in_kind == "Ia":
        a_I, bI1, bI2 = inner_pattern[1], inner_pattern[2], inner_pattern[3]
        pts_inner_d2 = [
            D_BB(a_I, m, r),
            D_BB((m - a_I) % m, m, r),
            D_BA(bI1, m, r, phi),
            D_BA(bI2, m, r, phi),
        ]
    elif in_kind == "Ib":
        b1a, b1b, b2a, b2b = inner_pattern[1:]
        pts_inner_d2 = [
            D_BA(b1a, m, r, phi),
            D_BA(b1b, m, r, phi),
            D_BA(b2a, m, r, phi),
            D_BA(b2b, m, r, phi),
        ]
    res_o = max(pts_outer_d2) - min(pts_outer_d2) if pts_outer_d2 else 0.0
    res_i = max(pts_inner_d2) - min(pts_inner_d2) if pts_inner_d2 else 0.0
    return float(max(res_o, res_i))


# ------------------------------------------------------------------
# Main driver
# ------------------------------------------------------------------

def main():
    M_LIST = [14, 15, 16, 18, 20, 25, 30]
    t0 = time.time()
    output = {
        "task": "Two-orbit ansatz at large m (Erdős Problem #97)",
        "date": "2026-05-06",
        "m_values": M_LIST,
        "setup": {
            "outer_radius_R": 1.0,
            "inner_radius": "r_b",
            "offset": "pi/m + phi",
            "free_parameters": ["r_b", "phi"],
            "convex_window": "(cos(pi/m), sec(pi/m))",
            "natural_cyclic_order": "A_0, B_0, A_1, B_1, ..., A_{m-1}, B_{m-1}",
        },
        "patterns_tested": {
            "Oa": "2 outer + 2 inner at A_0 (pair-classes (a, m-a) and (b, -1-b))",
            "Ob": "0 outer + 4 inner at A_0 (two distinct inner pair-classes)",
            "Ia": "2 inner + 2 outer at B_0 (pair-classes (a, m-a) and (b, 1-b))",
            "Ib": "0 inner + 4 outer at B_0 (two distinct outer pair-classes)",
            "combinations": "Oa+Ia, Ob+Ia, Oa+Ib, Ob+Ib all enumerated.",
        },
        "results": {},
    }
    for m in M_LIST:
        print(f"=== m = {m} (n = {2 * m}) ===", flush=True)
        res = search_m(m)
        print(
            f"  total candidates={res['n_candidates']}, "
            f"in window={res['n_in_convex_window']}, "
            f"strictly convex={res['n_strictly_convex']}, "
            f"survivors={len(res['survivors'])}",
            flush=True,
        )
        if res["best_record_in_window"] is not None:
            br = res["best_record_in_window"]
            print(
                f"  best in window: r_b={br.get('r'):.6f} phi={br.get('phi'):.6f} "
                f"witness_resid={br.get('witness_residual_spread')} "
                f"convex={br.get('strictly_convex_alternating')} "
                f"4bad={br.get('all_vertex_4bad')}",
                flush=True,
            )
        output["results"][str(m)] = res

    output["wall_time_sec"] = time.time() - t0
    output["summary"] = build_summary(output["results"])

    out_path = "/home/user/erdos97/data/certificates/2026-05-06/two_orbit_large_m.json"
    with open(out_path, "w") as f:
        json.dump(output, f, indent=2, default=str)
    print(f"\nWrote {out_path}", flush=True)
    print(f"Wall time: {output['wall_time_sec']:.1f}s", flush=True)


def build_summary(results_dict):
    total_survivors = 0
    total_near = 0
    per_m = {}
    for k, v in results_dict.items():
        total_survivors += len(v["survivors"])
        total_near += len(v["near_misses_in_window"])
        per_m[k] = {
            "n_candidates": v["n_candidates"],
            "n_in_convex_window": v["n_in_convex_window"],
            "n_strictly_convex": v["n_strictly_convex"],
            "survivors": len(v["survivors"]),
            "best_residual_in_window": v["best_residual_in_window"],
            "best_in_window": v["best_record_in_window"],
        }
    return {
        "total_survivors_over_all_m": total_survivors,
        "total_near_misses_in_window": total_near,
        "per_m": per_m,
        "verdict": (
            "two-orbit ansatz at large m has no strictly-convex 4-bad survivor"
            if total_survivors == 0
            else "candidate survivor(s) found - verify"
        ),
    }


if __name__ == "__main__":
    main()
