#!/usr/bin/env python3
"""Cyclic Sidon 4-offset sweep for Erdős Problem #97.

Enumerates Sidon 4-offset multisets D = {d_1,...,d_4} with 1 <= d_i < n/2 for
each n in a list of primes, building the symmetric pattern
    S_i = {(i + d) mod n : d in D union -D}
and applying a sequence of incidence filters:

  1. Sidon test on the 12 signed differences of (D union -D).
  2. |S_i cap S_j| <= 2 (pair-overlap cap).
  3. Adjacent-row two-overlap (crossing-bisector natural-order test).
  4. Altman natural-order linear certificate.
  5. Mutual-rhombus midpoint forced-equality classes.
  6. Odd-cycle and phi4-rectangle traps from filter_summary.

One representative per dihedral orbit (action: D -> a*D mod n for a in (Z/n)*,
plus negation D -> -D) is taken.  Survivors at every filter level are reported
and the full sweep is saved to JSON for replay.
"""
from __future__ import annotations

import json
import sys
from itertools import combinations
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from erdos97.altman_diagonal_sums import (  # noqa: E402
    altman_order_linear_certificate,
)
from erdos97.incidence_filters import filter_summary  # noqa: E402


def signed_offsets(D: tuple[int, ...], n: int) -> list[int]:
    """Return the symmetric 8-multiset D union -D of signed residues mod n."""
    out: set[int] = set()
    for d in D:
        out.add(d % n)
        out.add((-d) % n)
    return sorted(out)


def is_sidon(D: tuple[int, ...], n: int) -> bool:
    """All 12 ordered nonzero differences of D union -D distinct mod n.

    For 4 distinct values, an unordered pair (i,j) gives ±(d_i-d_j); we want
    every signed difference among the 8-set D union -D to be distinct,
    excluding the trivial 8 zeros and the 8 differences of the form d - (-d).
    Operationally, we require:
      * D itself has 12 distinct ordered differences (B_2[1] mod n in D)
        i.e. d_i - d_j for i != j are pairwise distinct; AND
      * pairwise sums d_i + d_j (i < j) are distinct, with no d_i + d_j == 0
        and 2*d_i not equal to d_j + d_k for distinct i,j,k.
    These guarantee that S_i is a 4-set and that |S_a cap S_b| <= 2.
    """
    # 1. Differences of D distinct mod n.
    diffs: set[int] = set()
    for i, di in enumerate(D):
        for j, dj in enumerate(D):
            if i == j:
                continue
            r = (di - dj) % n
            if r in diffs:
                return False
            diffs.add(r)
    # 2. Sums d_i + d_j (i < j) distinct mod n -- this is needed because
    #    differences across D and -D give d_i + d_j as well.
    sums: set[int] = set()
    for i, di in enumerate(D):
        for j, dj in enumerate(D):
            if i >= j:
                continue
            r = (di + dj) % n
            if r in sums:
                return False
            sums.add(r)
    # 3. No d_i + d_j == 0 mod n -- otherwise -d_j == d_i and the symmetric
    #    set is too small.
    for i, di in enumerate(D):
        for j, dj in enumerate(D):
            if i == j:
                continue
            if (di + dj) % n == 0:
                return False
    # 4. Symmetric set has 8 distinct residues (which the above ensures, but
    #    we double-check).
    sym = signed_offsets(D, n)
    if len(sym) != 8:
        return False
    return True


def build_symmetric_pattern(D: tuple[int, ...], n: int) -> list[list[int]]:
    sym = signed_offsets(D, n)
    return [sorted((i + d) % n for d in sym) for i in range(n)]


def pair_overlap_max(S: list[list[int]]) -> int:
    sets = [set(row) for row in S]
    n = len(S)
    m = 0
    for a in range(n):
        for b in range(a + 1, n):
            c = len(sets[a] & sets[b])
            if c > m:
                m = c
    return m


def adjacent_two_overlap_count(S: list[list[int]]) -> int:
    sets = [set(row) for row in S]
    n = len(S)
    return sum(1 for i in range(n) if len(sets[i] & sets[(i + 1) % n]) >= 2)


def canonical_orbit_rep(D: tuple[int, ...], n: int) -> tuple[int, ...]:
    """Canonical representative of D under multiplicative + negation action.

    The dihedral orbit on cyclic offsets is generated by D -> a*D mod n for
    a in (Z/n)* and D -> -D mod n.  We return the lexicographically smallest
    sorted 4-tuple over this orbit, where each candidate set is folded to
    representatives in [1, (n-1)//2] by reflecting d -> n-d when needed.
    """
    half = n // 2
    best: tuple[int, ...] | None = None
    for a in range(1, n):
        # gcd(a, n) needs to be 1 (n prime here, so any nonzero a works for the
        # multiplicative orbit). Apply both signs implicitly via reflection.
        scaled: set[int] = set()
        for d in D:
            r = (a * d) % n
            if r == 0:
                scaled = set()
                break
            if r > half:
                r = n - r
            scaled.add(r)
        if len(scaled) != 4:
            continue
        cand = tuple(sorted(scaled))
        if best is None or cand < best:
            best = cand
    assert best is not None
    return best


def enumerate_sidon_4_sets(n: int) -> list[tuple[int, ...]]:
    """Enumerate canonical Sidon 4-sets D in [1, (n-1)//2]."""
    half = (n - 1) // 2
    seen: set[tuple[int, ...]] = set()
    for combo in combinations(range(1, half + 1), 4):
        if not is_sidon(combo, n):
            continue
        canon = canonical_orbit_rep(combo, n)
        if canon in seen:
            continue
        # Re-test the canonical representative to ensure consistency.
        if not is_sidon(canon, n):
            continue
        seen.add(canon)
    return sorted(seen)


def evaluate_candidate(D: tuple[int, ...], n: int) -> dict:
    S = build_symmetric_pattern(D, n)
    overlap = pair_overlap_max(S)
    record: dict = {
        "D": list(D),
        "n": n,
        "max_pair_overlap": overlap,
        "passes_pair_overlap": overlap <= 2,
    }
    if overlap > 2:
        record["status"] = "killed_pair_overlap"
        return record

    adj = adjacent_two_overlap_count(S)
    record["adjacent_two_overlap_count"] = adj
    record["passes_adjacent_overlap"] = adj == 0

    summary = filter_summary(S)
    record["midpoint_matrix_rank"] = int(summary["midpoint_matrix_rank"])
    record["forced_equality_classes"] = summary["forced_equality_classes"]
    record["odd_cycle_length"] = summary["odd_cycle_length"]
    record["mutual_phi_2_cycles"] = summary["mutual_phi_2_cycles"]
    record["rectangle_trap_4_cycles"] = summary["rectangle_trap_4_cycles"]
    record["adjacent_two_overlap_violations"] = len(
        summary["adjacent_two_overlap_violations"]
    )
    record["crossing_bisector_violations"] = len(
        summary["crossing_bisector_violations"]
    )
    record["passes_mutual_rhombus"] = not summary["forced_equality_classes"]
    record["passes_odd_cycle"] = not summary["odd_cycle_length"]
    record["passes_rect4"] = not summary["rectangle_trap_4_cycles"]

    # Run Altman natural-order linear certificate as a heavier filter.
    # For larger n this is moderately expensive but still tractable.
    try:
        cert = altman_order_linear_certificate(
            S, order=list(range(n)), pattern=f"C{n}_sidon_{'_'.join(map(str, D))}"
        )
        record["altman_obstructed"] = bool(cert.obstructed)
        record["altman_status"] = cert.status
        record["altman_certificate_method"] = cert.certificate_method
    except Exception as exc:  # pragma: no cover
        record["altman_obstructed"] = None
        record["altman_status"] = "ERROR"
        record["altman_error"] = str(exc)
    record["passes_altman_natural"] = not record.get("altman_obstructed", True)

    survives = (
        record["passes_pair_overlap"]
        and record["passes_adjacent_overlap"]
        and record["passes_mutual_rhombus"]
        and record["passes_odd_cycle"]
        and record["passes_rect4"]
        and record["passes_altman_natural"]
    )
    record["survives_all"] = bool(survives)
    record["status"] = "survivor" if survives else "killed_by_filter"
    return record


def sweep(primes: Iterable[int]) -> dict:
    by_n: dict[str, dict] = {}
    for n in primes:
        cands = enumerate_sidon_4_sets(n)
        records = [evaluate_candidate(D, n) for D in cands]
        survivors = [rec for rec in records if rec.get("survives_all")]
        by_n[str(n)] = {
            "n": n,
            "candidate_count": len(cands),
            "candidates": records,
            "survivor_count": len(survivors),
            "survivors": survivors,
        }
    return {
        "primes": list(primes),
        "by_n": by_n,
    }


def main() -> int:
    primes = [31, 37, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
    out = ROOT / "data" / "certificates" / "2026-05-06" / "cyclic_sidon_sweep.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    result = sweep(primes)

    counts: list[tuple[int, int, int]] = []
    for n in primes:
        block = result["by_n"][str(n)]
        counts.append((n, block["candidate_count"], block["survivor_count"]))

    summary_lines = ["n, candidates, survivors"]
    for n, ck, sk in counts:
        summary_lines.append(f"{n}, {ck}, {sk}")
    print("\n".join(summary_lines))

    out.write_text(json.dumps(result, indent=2, sort_keys=True), encoding="utf-8")
    print(f"\nwrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
