#!/usr/bin/env python3
"""Generate file and session navigation without changing research claims."""
from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from pathlib import Path
import re
import subprocess
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
INVENTORY = ROOT / 'docs/inventory.md'
LOG_INDEX = ROOT / 'reports/research-log-index.md'


def tracked_and_new() -> list[str]:
    paths = set()
    for flags in [[], ['--others', '--exclude-standard']]:
        output = subprocess.check_output(['git', 'ls-files', '-z', *flags], cwd=ROOT)
        paths.update(p for p in output.decode().split('\0') if p)
    return sorted(p for p in paths if (ROOT / p).is_file())


def inventory_text(paths: list[str]) -> str:
    docs = sorted(p for p in paths if p.startswith('docs/') and Path(p).suffix in {'.md', '.html'} and p != 'docs/inventory.md')
    lines = ['# Complete documentation inventory', '',
             'Generated by `python scripts/generate_navigation.py --write`; do not edit.',
             'Navigation only. [Topic map](index.md) | [Annotated catalogue](catalogue.md)', '',
             f'{len(docs)} documentation files, excluding this inventory itself.', '']
    for path in docs:
        relative = path.removeprefix('docs/')
        lines.append(f'- [{relative}]({quote(relative)})')
    return '\n'.join(lines) + '\n'


def session_entries(text: str) -> list[tuple[str, str, str]]:
    """Index level-two sessions, respecting duplicate heading anchors and fences."""
    counts: Counter[str] = Counter()
    entries = []
    fence = None
    for line in text.splitlines():
        marker = re.match(r'^\s{0,3}(`{3,}|~{3,})', line)
        if marker:
            run = marker.group(1)
            if fence is None:
                fence = run
            elif run[0] == fence[0] and len(run) >= len(fence):
                fence = None
            continue
        if fence is not None:
            continue
        heading = re.match(r'^(#{1,6})\s+(.+?)(?:\s+#+)?\s*$', line)
        if not heading:
            continue
        title = heading.group(2)
        slug = re.sub(r'[^\w\- ]', '', title.lower()).replace(' ', '-')
        suffix = counts[slug]
        counts[slug] += 1
        anchor = slug + (f'-{suffix}' if suffix else '')
        if heading.group(1) == '##':
            match = re.search(r'\b\d{4}-\d{2}-\d{2}\b', title)
            entries.append((match.group() if match else 'Undated', title, anchor))
    return entries


def log_text(paths: list[str]) -> str:
    sources = [p for p in paths if p == 'reports/codex_goal_erdos97_log.md' or (p.startswith('reports/research-log/') and p.endswith('.md'))]
    groups = defaultdict(list)
    for source in sources:
        for day, title, anchor in session_entries((ROOT / source).read_text(encoding='utf-8')):
            target = quote(source.removeprefix('reports/')) + '#' + quote(anchor)
            groups[day].append(f'- [{title}]({target})')
    lines = ['# Research session index', '',
             'Generated by `python scripts/generate_navigation.py --write`; do not edit.',
             'Historical navigation only. Entries are not accepted mathematical claims.',
             '[Current state](../STATE.md) | [Research topics](../docs/index.md)', '',
             'Expand a date, then select a session/topic. Original files and anchors are retained.', '']
    for day in sorted(groups, reverse=True):
        lines.extend(['<details>', f'<summary>{day} ({len(groups[day])} sessions)</summary>', '', *groups[day], '', '</details>', ''])
    return '\n'.join(lines) + '\n'


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--write', action='store_true')
    mode.add_argument('--check', action='store_true')
    args = parser.parse_args()
    paths = tracked_and_new()
    outputs = {INVENTORY: inventory_text(paths), LOG_INDEX: log_text(paths)}
    stale = []
    for path, expected in outputs.items():
        if args.write:
            path.write_text(expected, encoding='utf-8', newline='\n')
        elif not path.exists() or path.read_text(encoding='utf-8') != expected:
            stale.append(str(path.relative_to(ROOT)))
    if stale:
        print('Stale navigation: ' + ', '.join(stale) + '; run scripts/generate_navigation.py --write')
        return 1
    print('Navigation generated' if args.write else 'Navigation is current')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
