"""Exact Kalmanson endgames for the fragile-cycle three-halo deep frontier.

The source packet contains thirteen fixed eight-row partial selected-witness
systems on ten cyclically ordered labels.  This module quotients ordinary
pair-distance variables by those partial selected equalities and extracts a
minimum selected-row core supporting either one strict Kalmanson self-edge or
an exact two-row inverse pair.

Everything here is a bounded fixed-order certificate diagnostic.  In
particular, the module does not force the source quotient from geometry and
does not claim an ``n=10`` or general theorem.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from hashlib import sha256
from itertools import combinations
import json
import math
from typing import Any, Mapping, Sequence

from erdos97.quotient_cone import (
    DistanceQuotient,
    KALMANSON_KINDS,
    UnionFind,
    kalmanson_row,
    kalmanson_terms,
    pair,
)


N = 10
SOURCE_SCHEMA = "erdos97.fragile_cycle_three_halo_deep_frontier.v1"
SOURCE_CATALOG_SHA256 = (
    "73e1cabd1670fddd3452bba72c80880f3eeebbc574a4873de3905a1c33781765"
)
SCHEMA = "erdos97.fragile_cycle_three_halo_kalmanson_endgame.v1"
STATUS = "EXACT_BOUNDED_FIXED_ORDER_KALMANSON_ENDGAME"
TRUST = "EXACT_CERTIFICATE_DIAGNOSTIC"
CLAIM_SCOPE = (
    "Exact natural-order Kalmanson certificates for the thirteen fixed "
    "eight-row states in the fragile-cycle three-halo deep-frontier packet. "
    "Each certificate applies only to its encoded partial selected-row "
    "system and cyclic order. This does not force the quotient or halo "
    "placement from minimal-counterexample geometry, does not prove n=10 or "
    "Erdos Problem #97, and is not a counterexample."
)
CONCLUSION = (
    "Every stored clean eight-row three-halo frontier state contains a "
    "three-selected-row natural-order Kalmanson obstruction: eleven use one "
    "strict self-edge and two use an exact two-inequality inverse pair."
)
PROVENANCE = {
    "generator": "scripts/check_fragile_cycle_three_halo_kalmanson_endgame.py",
    "command": (
        "python scripts/check_fragile_cycle_three_halo_kalmanson_endgame.py "
        "--write --assert-expected --summary-json"
    ),
}

EXPECTED_STATE_COUNT = 13
EXPECTED_SELF_EDGE_STATE_COUNT = 11
EXPECTED_INVERSE_PAIR_STATE_COUNT = 2
EXPECTED_CORE_WIDTH = 3
EXPECTED_TOTAL_STRICT_ROWS = 15
EXPECTED_KIND_COUNTS = {
    "K1_diag_gt_sides": 4,
    "K2_diag_gt_other": 11,
}
EXPECTED_CATALOG_SHA256 = (
    "b624cc8772fc50bd2cd924608b35e8769b6aa717167814d84936348fb9501eb5"
)

CenteredRow = tuple[int, tuple[int, int, int, int]]


@dataclass(frozen=True)
class StrictCandidate:
    """One natural-order strict Kalmanson row in a partial quotient."""

    index: int
    kind: str
    quad: tuple[int, int, int, int]
    vector: tuple[int, ...]


def partial_distance_quotient(
    n: int,
    rows: Sequence[CenteredRow],
) -> DistanceQuotient:
    """Build the selected-distance quotient generated by centered partial rows."""

    if n < 5:
        raise ValueError("partial selected-row quotient requires at least 5 labels")
    centers: set[int] = set()
    normalized_rows: list[CenteredRow] = []
    for raw_center, raw_witnesses in rows:
        center = int(raw_center)
        witnesses = tuple(int(label) for label in raw_witnesses)
        if center in centers:
            raise ValueError(f"duplicate partial-row center: {center}")
        if center < 0 or center >= n:
            raise ValueError(f"partial-row center outside 0..{n - 1}: {center}")
        if len(witnesses) != 4 or len(set(witnesses)) != 4:
            raise ValueError(f"center {center} does not have four distinct witnesses")
        if center in witnesses:
            raise ValueError(f"center {center} occurs in its witness row")
        if any(label < 0 or label >= n for label in witnesses):
            raise ValueError(f"center {center} has witness outside 0..{n - 1}")
        centers.add(center)
        normalized_rows.append((center, witnesses))

    all_pairs = [pair(left, right) for left, right in combinations(range(n), 2)]
    quotient = UnionFind(all_pairs)
    for center, witnesses in normalized_rows:
        base = pair(center, witnesses[0])
        for witness in witnesses[1:]:
            quotient.union(base, pair(center, witness))

    root_index: dict[tuple[int, int], int] = {}
    pair_class: dict[tuple[int, int], int] = {}
    members: dict[int, list[tuple[int, int]]] = {}
    for distance_pair in all_pairs:
        root = quotient.find(distance_pair)
        class_index = root_index.setdefault(root, len(root_index))
        pair_class[distance_pair] = class_index
        members.setdefault(class_index, []).append(distance_pair)
    class_members = tuple(tuple(members[index]) for index in range(len(members)))
    return DistanceQuotient(
        n=n,
        pair_class=pair_class,
        class_members=class_members,
    )


def _source_rows(record: Mapping[str, Any]) -> tuple[CenteredRow, ...]:
    raw_rows = record.get("selected_rows_natural_order")
    if not isinstance(raw_rows, list):
        raise ValueError("deep-frontier state has no natural-order row list")
    rows: list[CenteredRow] = []
    for raw_row in raw_rows:
        if not isinstance(raw_row, list) or len(raw_row) != 5:
            raise ValueError("deep-frontier selected row must have five entries")
        rows.append(
            (
                int(raw_row[0]),
                (
                    int(raw_row[1]),
                    int(raw_row[2]),
                    int(raw_row[3]),
                    int(raw_row[4]),
                ),
            )
        )
    partial_distance_quotient(N, rows)
    return tuple(sorted(rows))


def _candidate_catalog(quotient: DistanceQuotient) -> tuple[StrictCandidate, ...]:
    candidates: list[StrictCandidate] = []
    for quad in combinations(range(quotient.n), 4):
        for kind in KALMANSON_KINDS:
            strict_row = kalmanson_row(quotient, kind, quad)
            candidates.append(
                StrictCandidate(
                    index=len(candidates),
                    kind=kind,
                    quad=quad,
                    vector=strict_row.vector,
                )
            )
    return tuple(candidates)


def _inverse_weights(
    left: Sequence[int],
    right: Sequence[int],
) -> tuple[int, int] | None:
    """Return primitive positive weights when two nonzero vectors cancel."""

    first = next(
        (
            (left_value, right_value)
            for left_value, right_value in zip(left, right, strict=True)
            if left_value or right_value
        ),
        None,
    )
    if first is None:
        return None
    left_value, right_value = first
    if left_value == 0 or right_value == 0 or left_value * right_value >= 0:
        return None
    divisor = math.gcd(abs(left_value), abs(right_value))
    left_weight = abs(right_value) // divisor
    right_weight = abs(left_value) // divisor
    if all(
        left_weight * lhs + right_weight * rhs == 0
        for lhs, rhs in zip(left, right, strict=True)
    ):
        return left_weight, right_weight
    return None


def _obstructions(
    candidates: Sequence[StrictCandidate],
    strict_support: int,
) -> list[tuple[tuple[int, int], ...]]:
    if strict_support == 1:
        return [
            ((candidate.index, 1),)
            for candidate in candidates
            if not any(candidate.vector)
        ]
    if strict_support != 2:
        raise ValueError(f"unsupported strict support: {strict_support}")
    out: list[tuple[tuple[int, int], ...]] = []
    for left_index, left in enumerate(candidates):
        if not any(left.vector):
            continue
        for right in candidates[left_index + 1 :]:
            weights = _inverse_weights(left.vector, right.vector)
            if weights is not None:
                out.append(
                    (
                        (left.index, weights[0]),
                        (right.index, weights[1]),
                    )
                )
    return out


def _minimum_core(
    rows: Sequence[CenteredRow],
) -> tuple[
    tuple[CenteredRow, ...],
    tuple[tuple[int, int], ...],
    dict[str, int],
    int,
    int,
]:
    full_quotient = partial_distance_quotient(N, rows)
    full_candidates = _candidate_catalog(full_quotient)
    full_self_edges = _obstructions(full_candidates, 1)
    strict_support = 1 if full_self_edges else 2
    full_obstructions = (
        full_self_edges
        if full_self_edges
        else _obstructions(full_candidates, strict_support)
    )
    if not full_obstructions:
        raise AssertionError("deep state has no one- or two-row Kalmanson obstruction")

    row_by_center = {center: witnesses for center, witnesses in rows}
    centers = sorted(row_by_center)
    subsets_checked: dict[str, int] = {}
    for width in range(len(centers) + 1):
        hits: list[
            tuple[
                tuple[int, ...],
                tuple[tuple[int, int], ...],
            ]
        ] = []
        subsets = list(combinations(centers, width))
        subsets_checked[str(width)] = len(subsets)
        for subset in subsets:
            core_rows = tuple((center, row_by_center[center]) for center in subset)
            quotient = partial_distance_quotient(N, core_rows)
            candidates = _candidate_catalog(quotient)
            for obstruction in _obstructions(candidates, strict_support):
                hits.append((subset, obstruction))
        if hits:
            hits.sort()
            subset, obstruction = hits[0]
            core_rows = tuple((center, row_by_center[center]) for center in subset)
            return (
                core_rows,
                obstruction,
                subsets_checked,
                len(hits),
                len(full_obstructions),
            )
    raise AssertionError("full obstruction has no selected-row support")


def _sparse_vector(vector: Sequence[int]) -> dict[str, int]:
    return {
        str(index): int(value)
        for index, value in enumerate(vector)
        if value != 0
    }


def _strict_item(
    candidate: StrictCandidate,
    weight: int,
    order: Sequence[int],
) -> dict[str, Any]:
    terms = kalmanson_terms(candidate.kind, candidate.quad)
    return {
        "source": "kalmanson",
        "kind": candidate.kind,
        "quad_natural_order": list(candidate.quad),
        "quad_original_labels": [int(order[label]) for label in candidate.quad],
        "weight": int(weight),
        "positive_pairs_natural_order": [
            list(distance_pair) for distance_pair, coefficient in terms if coefficient > 0
        ],
        "negative_pairs_natural_order": [
            list(distance_pair) for distance_pair, coefficient in terms if coefficient < 0
        ],
        "reduced_nonzero_coefficients": _sparse_vector(candidate.vector),
    }


def replay_kalmanson_certificate(
    n: int,
    certificate: Mapping[str, Any],
) -> dict[str, Any]:
    """Independently replay one stored partial-row Kalmanson certificate."""

    raw_rows = certificate.get("selected_core_rows_natural_order")
    raw_strict_rows = certificate.get("strict_rows")
    if not isinstance(raw_rows, list) or not isinstance(raw_strict_rows, list):
        raise ValueError("certificate needs selected core rows and strict rows")
    rows = _source_rows({"selected_rows_natural_order": raw_rows})
    quotient = partial_distance_quotient(n, rows)
    total = [0] * quotient.class_count
    kind_counts: Counter[str] = Counter()
    for raw_item in raw_strict_rows:
        if not isinstance(raw_item, Mapping):
            raise ValueError("strict certificate row must be an object")
        kind = str(raw_item["kind"])
        quad = tuple(int(label) for label in raw_item["quad_natural_order"])
        if kind not in KALMANSON_KINDS:
            raise ValueError(f"unknown Kalmanson kind: {kind}")
        if len(quad) != 4 or tuple(sorted(quad)) != quad:
            raise ValueError(f"quadrilateral is not in natural cyclic order: {quad}")
        weight = int(raw_item["weight"])
        if weight <= 0:
            raise ValueError("strict-row weight must be positive")
        candidate = kalmanson_row(quotient, kind, quad)
        if _sparse_vector(candidate.vector) != raw_item.get(
            "reduced_nonzero_coefficients"
        ):
            raise AssertionError("stored strict-row quotient vector drift")
        for index, value in enumerate(candidate.vector):
            total[index] += weight * value
        kind_counts[kind] += 1
    if not raw_strict_rows:
        raise ValueError("certificate has no strict Kalmanson rows")
    if any(total):
        raise AssertionError("strict Kalmanson combination does not reduce to zero")
    return {
        "selected_core_row_count": len(rows),
        "strict_row_count": len(raw_strict_rows),
        "distance_class_count": quotient.class_count,
        "kind_counts": dict(sorted(kind_counts.items())),
        "combined_nonzero_coefficient_count": 0,
        "zero_sum_verified": True,
    }


def _validate_source(source: Mapping[str, Any]) -> None:
    if source.get("schema") != SOURCE_SCHEMA:
        raise ValueError("unexpected three-halo deep-frontier source schema")
    if source.get("deep_frontier_catalog_sha256") != SOURCE_CATALOG_SHA256:
        raise ValueError("unexpected three-halo deep-frontier source digest")
    states = source.get("deep_frontier_states")
    if not isinstance(states, list) or len(states) != EXPECTED_STATE_COUNT:
        raise ValueError("unexpected three-halo deep-frontier state catalog")


def kalmanson_endgame_payload(source: Mapping[str, Any]) -> dict[str, Any]:
    """Build the minimized exact Kalmanson packet for all deep states."""

    _validate_source(source)
    certificates: list[dict[str, Any]] = []
    kind_counts: Counter[str] = Counter()
    strict_support_counts: Counter[int] = Counter()
    core_width_counts: Counter[int] = Counter()
    terminal_crosswalk: Counter[str] = Counter()
    for record in source["deep_frontier_states"]:
        if not isinstance(record, Mapping):
            raise ValueError("deep-frontier state record must be an object")
        rows = _source_rows(record)
        order = tuple(int(label) for label in record["cyclic_order"])
        if len(order) != N or len(set(order)) != N:
            raise ValueError("source cyclic order is not a ten-label permutation")
        (
            core_rows,
            obstruction,
            subsets_checked,
            minimum_candidate_count,
            full_obstruction_count,
        ) = _minimum_core(rows)
        quotient = partial_distance_quotient(N, core_rows)
        catalog = _candidate_catalog(quotient)
        strict_rows = [
            _strict_item(catalog[index], weight, order)
            for index, weight in obstruction
        ]
        certificate: dict[str, Any] = {
            "state_id": str(record["state_id"]),
            "source_terminal_type": str(record["terminal_type"]),
            "halo_gaps": [int(gap) for gap in record["halo_gaps"]],
            "cyclic_order": list(order),
            "source_selected_row_count": len(rows),
            "obstruction_type": (
                "strict_kalmanson_self_edge"
                if len(strict_rows) == 1
                else "strict_kalmanson_inverse_pair"
            ),
            "selected_core_rows_natural_order": [
                [center, *witnesses] for center, witnesses in core_rows
            ],
            "selected_core_rows_original_labels": [
                [
                    order[center],
                    *sorted(order[witness] for witness in witnesses),
                ]
                for center, witnesses in core_rows
            ],
            "selected_core_row_count": len(core_rows),
            "strict_rows": strict_rows,
            "strict_row_count": len(strict_rows),
            "minimum_core_search": {
                "subsets_checked_by_width": subsets_checked,
                "strict_candidate_count_at_minimum_width": minimum_candidate_count,
                "full_state_obstruction_count_at_minimum_strict_support": (
                    full_obstruction_count
                ),
                "minimality": (
                    "All selected-row subsets of smaller cardinality were "
                    "exhausted; every obstruction at the first successful "
                    "width was enumerated before deterministic selection."
                ),
            },
        }
        certificate["independent_replay"] = replay_kalmanson_certificate(
            N, certificate
        )
        certificates.append(certificate)
        strict_support_counts[len(strict_rows)] += 1
        core_width_counts[len(core_rows)] += 1
        terminal_crosswalk[str(record["terminal_type"])] += 1
        kind_counts.update(item["kind"] for item in strict_rows)

    catalog_material = {"state_certificates": certificates}
    catalog_digest = sha256(
        json.dumps(catalog_material, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()
    return {
        "schema": SCHEMA,
        "status": STATUS,
        "trust": TRUST,
        "claim_scope": CLAIM_SCOPE,
        "source_artifact": {
            "path": (
                "data/certificates/fragile_cycle_three_halo_deep_frontier.json"
            ),
            "schema": SOURCE_SCHEMA,
            "deep_frontier_catalog_sha256": SOURCE_CATALOG_SHA256,
        },
        "certificate_contract": {
            "n": N,
            "cyclic_order_rule": (
                "Relabel each source halo placement by its stored natural "
                "cyclic order 0,1,...,9."
            ),
            "strict_row_family": (
                "Both strict Kalmanson inequalities for every four-label "
                "subsequence of the natural cyclic order."
            ),
            "strict_candidate_count": 2 * math.comb(N, 4),
            "allowed_strict_support": [1, 2],
            "selected_core_rule": (
                "Minimize selected-row cardinality at the state's minimum "
                "strict support; exhaust and count all hits at that width."
            ),
            "coefficient_arithmetic": "exact integers",
        },
        "state_certificate_count": len(certificates),
        "state_certificates": certificates,
        "strict_support_histogram": {
            str(width): count for width, count in sorted(strict_support_counts.items())
        },
        "selected_core_width_histogram": {
            str(width): count for width, count in sorted(core_width_counts.items())
        },
        "strict_kind_counts": dict(sorted(kind_counts.items())),
        "source_terminal_type_crosswalk": dict(sorted(terminal_crosswalk.items())),
        "kalmanson_endgame_catalog_sha256": catalog_digest,
        "summary": {
            "deep_states_checked": len(certificates),
            "states_killed_by_one_strict_self_edge": strict_support_counts[1],
            "states_killed_by_two_strict_inverse_pair": strict_support_counts[2],
            "minimum_selected_core_width": min(core_width_counts),
            "maximum_selected_core_width": max(core_width_counts),
            "total_strict_rows_in_selected_certificates": sum(kind_counts.values()),
            "all_states_exactly_obstructed": len(certificates)
            == sum(strict_support_counts.values()),
            "all_selected_certificates_zero_sum": all(
                certificate["independent_replay"]["zero_sum_verified"]
                for certificate in certificates
            ),
        },
        "limitations": [
            "The packet starts from the thirteen stored fixed three-halo deep-frontier states; it does not force any state from geometry.",
            "Every certificate uses the cyclic order attached to its source halo placement; no all-order statement is claimed.",
            "The three-row core conclusion is a finite catalog compression, not a universal fragile-cycle lemma.",
            "No proof of n=10, general proof, counterexample, or official/global status update is claimed.",
        ],
        "conclusion": CONCLUSION,
        "provenance": PROVENANCE,
    }


def assert_expected_payload(payload: Mapping[str, Any]) -> None:
    """Check stable exact anchors and replay every selected certificate."""

    assert payload["schema"] == SCHEMA
    assert payload["status"] == STATUS
    assert payload["trust"] == TRUST
    assert payload["claim_scope"] == CLAIM_SCOPE
    assert payload["state_certificate_count"] == EXPECTED_STATE_COUNT
    assert payload["strict_support_histogram"] == {
        "1": EXPECTED_SELF_EDGE_STATE_COUNT,
        "2": EXPECTED_INVERSE_PAIR_STATE_COUNT,
    }
    assert payload["selected_core_width_histogram"] == {
        str(EXPECTED_CORE_WIDTH): EXPECTED_STATE_COUNT
    }
    assert payload["strict_kind_counts"] == EXPECTED_KIND_COUNTS
    summary = payload["summary"]
    assert summary["deep_states_checked"] == EXPECTED_STATE_COUNT
    assert (
        summary["states_killed_by_one_strict_self_edge"]
        == EXPECTED_SELF_EDGE_STATE_COUNT
    )
    assert (
        summary["states_killed_by_two_strict_inverse_pair"]
        == EXPECTED_INVERSE_PAIR_STATE_COUNT
    )
    assert summary["minimum_selected_core_width"] == EXPECTED_CORE_WIDTH
    assert summary["maximum_selected_core_width"] == EXPECTED_CORE_WIDTH
    assert (
        summary["total_strict_rows_in_selected_certificates"]
        == EXPECTED_TOTAL_STRICT_ROWS
    )
    assert summary["all_states_exactly_obstructed"] is True
    assert summary["all_selected_certificates_zero_sum"] is True
    assert (
        payload["kalmanson_endgame_catalog_sha256"]
        == EXPECTED_CATALOG_SHA256
    )
    certificates = payload["state_certificates"]
    assert len(certificates) == EXPECTED_STATE_COUNT
    for certificate in certificates:
        assert replay_kalmanson_certificate(N, certificate) == certificate[
            "independent_replay"
        ]
    assert payload["conclusion"] == CONCLUSION
    assert payload["provenance"] == PROVENANCE
